name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: "!**/.nuget/packages/**/*.*"
        flags: ${{ runner.os }},${{ matrix.dotnet.framework }
